function dyad = construct_dyad()
    % dyad = struct( ...
    %     'A', struct( ...
    %         'index', 1, ...
    %         'name', "Alice", ...
    %         'delta', 3, ...
    %         'deltarange', 4, ...
    %         'pref_mode', "exp", ...
    %         'color', "b", ...
    %         'class', 'agent' ...
    %     ), ...
    %     'B', struct( ...
    %         'index', 2, ...
    %         'name', "Neutral", ...
    %         'delta', 6, ... 
    %         'deltarange', 4, ...
    %         'pref_mode', "normdif", ...
    %         'color', [0 0.6 0], ...
    %         'class', 'agent', ... % Alternatives: bot, paradigmbot, ...
    %         'character', "avoidant" ...
    %     ) ...
    % );

    % Definition of the dyad
    dyad = struct( ...
        'A', struct( ...
            'index', 1, ...
            'name', "Alice", ...
            'delta', 10, ...
            'deltarange', 5, ...
            'pref_mode', "exp", ...
            'color', "b", ...
            'class', 'agent' ...
        ), ...
        'B', struct( ...
            'index', 2, ...
            'name', "Bob", ...
            'delta', 4, ...
            'deltarange', 5, ...
            'pref_mode', "exp", ...
            'color', "r", ...
            'class', 'agent' ...
        ) ...
    );

    %'character', "avoidant" "neutral" "anxious" "disorganised"




end