% Definition of the dyad (used all over the code)
function d = dyad()
    d = struct( ...
        'A', struct( ...
            'index', 1, ...
            'name', "Alice", ...
            'delta', 3, ...
            'deltarange', 2, ...
            'color', "b" ...
        ), ...
        'B', struct( ...
            'index', 2, ...
            'name', "Bob", ...
            'delta', NaN, ... % Bot
            'deltarange', NaN, ... %Bot
            'color', [0 0.6 0] ...
        ) ...
    );
end